spring:
  application:
    name: "gatewayserver"
  config:
    import: "optional:configserver:http://localhost:8071/"
  cloud:
    gateway:
      discovery:
        locator:
          enabled: false # hide the eureka servers paths
          lower-case-service-id: true

management:
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    gateway:
      enabled: true
  info: # info related actuator url
    env:
      enabled: true

info: # eureka server dashboard info
  app:
    name: "gatewayserver"
    description: "Spring Boot Demo Bank - Gateway Server"
    version: "1.0.0"

logging:
  level:
    com:
      artcorb:
        gatewayserver: DEBUG

resilience4j:
  circuitbreaker:
    configs:
      default:
        sliding-window-size: 10
        permitted-number-of-calls-in-half-open-state: 2
        failure-rate-threshold: 50
        wait-duration-in-open-state: 10000
